INSERT INTO dw.temperaturaexterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (-1, -1, '-1');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.0, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.1, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.2, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.3, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.4, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.5, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.6, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.7, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.8, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (0.9, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.0, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.1, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.2, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.3, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.4, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.5, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.6, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.7, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.8, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (1.9, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.0, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.1, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.2, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.3, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.4, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.5, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.6, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.7, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.8, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (2.9, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.0, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.1, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.2, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.3, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.4, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.5, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.6, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.7, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.8, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (3.9, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.0, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.1, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.2, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.3, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.4, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.5, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.6, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.7, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.8, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (4.9, 1, 'Baja');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (5.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (6.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (7.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (8.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (9.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (10.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (11.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (12.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (13.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.0, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.1, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.2, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.3, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.4, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.5, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.6, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.7, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.8, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (14.9, 2, 'Media');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (15.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (16.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (17.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (18.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (19.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (20.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (21.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (22.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (23.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.0, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.1, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.2, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.3, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.4, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.5, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.6, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.7, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.8, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (24.9, 3, 'Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (25.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (26.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (27.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (28.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (29.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (30.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (31.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (32.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (33.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (34.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (35.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (36.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (37.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (38.9, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.0, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.1, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.2, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.3, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.4, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.5, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.6, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.7, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.8, 4, 'Muy Alta');
INSERT INTO dw.temperaturaExterna(valorenc, idrangotemperaturaexterna, descrangotemperaturaexterna) VALUES (39.9, 4, 'Muy Alta');